import type { Metadata } from "next";
import { Prata, Nanum_Myeongjo, Inria_Serif } from "next/font/google";
import "./globals.css";
import { HeaderBar } from "@/components/main/HeaderBar";
import { MusicPlayer } from "@/components/reusable/CTA/MusicPlayer/MusicPlayer";

const prata = Prata({
  subsets: ["latin"],
  variable: "--font-prata",
  weight: ["400"],
});

const nanum = Nanum_Myeongjo({
  subsets: ["latin"],
  variable: "--font-nanum",
  weight: ["400", "700"],
});

const inria_serif = Inria_Serif({
  subsets: ["latin"],
  variable: "--font-inria-serif",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prata.className} ${nanum.className} ${inria_serif.className} antialiased`}
      >
        <HeaderBar />
        {children}  
        <MusicPlayer/>
      </body>
    </html>
  );
}
